version: '3'

tasks:
  generate-api:
    cmds:
      - go get github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen
      - go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen -package api -generate types,server,spec ./contracts/openapi.yaml > ./internal/transport/http/api/api.gen.go
      - go mod tidy
