app:
  name: "L0 TASK TEST"
  version: "1.0.0"
  env: "development"
  port: 80
  ssl_enable: false
  ssl_config:
    cert_path: /certs/fullchain.pem
    key_path: /certs/privkey.pem

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "l0_task_test"
  sslmode: "disable"
  max_open_conns: 20
  max_idle_conns: 5
  conn_max_lifetime: "1h"

kafka:
  brokers: "localhost:9092"
  topic: "orders.events"
  group_id: "orders-processor"

cache:
  type: "memory"       # memory | redis
  capacity: 1000
  memory:
    cleanup_interval: "5m"
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
    ttl: "10m"

cors:
  allow_origins: 
    - "http://localhost:80"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "Cache-Control"
    - "Pragma"
    - "Sec-Fetch-Dest"
    - "Sec-Fetch-Mode"
    - "Sec-Fetch-Site"
    - "User-Agent"
    - "sec-ch-ua"
    - "sec-ch-ua-mobile"
    - "sec-ch-ua-platform"
  allow_credentials: true
  max_age: "5m"  

log:
  level: "debug"
  format: "console"
  service_name: "L0_TASK_TEST"
  environment: "development"
  enable_caller: true